CREATING ENVIRONMENT
CREATING DQN
Traceback (most recent call last):
  File "/home/s1949624/RL_matching/experiments.py", line 59, in <module>
    main()
  File "/home/s1949624/RL_matching/experiments.py", line 50, in main
    dqn = DQN(SETTINGS, env)
          ^^^^^^^^^^^^^^^^^^
  File "/home/s1949624/RL_matching/dqn_torch.py", line 28, in __init__
    self.q_net.to('cuda')
  File "/local/s1949624/conda_envs/sanquin/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/local/s1949624/conda_envs/sanquin/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/local/s1949624/conda_envs/sanquin/lib/python3.11/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/local/s1949624/conda_envs/sanquin/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

